export const TICK = "TICK";
export const ON_HOVER_DAY = "ON_HOVER_DAY";
export const OFF_HOVER_DAY = "OFF_HOVER_DAY";
export const REQUEST_LOCATIONS = "REQUEST_LOCATIONS";
export const RECEIVE_LOCATIONS = "RECEIVE_LOCATIONS";
export const REQUEST_REPORT = "REQUEST_REPORT";
export const RECEIVE_REPORT = "RECEIVE_REPORT";
export const CLEAR_REPORT = "CLEAR_REPORT";
export const RECEIVE_BREAKS = "RECEIVE_BREAKS";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const CLICK_MENU_ITEM = "CLICK_MENU_ITEM";
export const RECEIVE_REPORT_DETAIL = "RECEIVE_REPORT_DETAIL";
export const CLOSE_REPORT = "CLOSE_REPORT";
export const CHANGE_FORECAST_DAY = "CHANGE_FORECAST_DAY";




